name: Build

on:
  push: { branches: [main] }


env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v2
        with:
          path: Hound Hunter/Library
          key: Library-${{ hashFiles('Hound Hunter/Assets/**', 'Hound Hunter/Packages/**', 'Hound Hunter/ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2020.3.25f1
          projectPath: Hound Hunter
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2020.3.25f1
          projectPath: Hound Hunter
          targetPlatform: WebGL 
          versioning: Semantic

      # Output 
   #   - uses: actions/upload-artifact@v2
      #  with:
      #    name: Build
       #   path: build
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
        with:
        # Name of the artifact to deploy
          artifact_name: github-pages # optional, default is github-pages


#      - name: Zip build
#        run: |
#          pushd build/StandaloneWindows64
#          zip -r ../../StandaloneWindows64.zip .
#          popd

#      - uses: actions/upload-artifact@v2
#        with:
#          name: Upload Build
#          path: StandaloneWindows64.zip
